Fix liter menu bug
Eucharistie/streaming-links pull request #79
Opened 2020-11-07 12:19 UTC by Dev1an

@duvrai

2020-11-07 22:06 UTC, duvrai requested changes
de update van annonciation.md werkt niet: als je youtubeChannelID toevoegt komt er een live player, maar die werkt niet voor dit kanaal

2020-11-07 23:35 UTC, Dev1an commented
OK ik heb die update van Annonciation (7758bb2) dan terug weggedaan uit deze branch. En ik heb uw semi-fix voor #73 erbij gezet (b24ee5c).

2020-11-08 00:42 UTC, d0rable commented
Ja ik snap niet hoe ik dat moet doen zodanig dat die player tevoorschijn komt. Is dit dan de verkeerde channelID ?

> Op 7 nov. 2020, om 23:07 heeft duvrai <notifications@github.com> het volgende geschreven:
> 
> 
> @duvrai requested changes on this pull request.
> 
> deze wijziging werkt niet: als je youtubeChannelID toevoegt komt er een live player, maar die werkt niet voor dit kanaal
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/Eucharistie/streaming-links/pull/79#pullrequestreview-525686659>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AO4SC65E2QUFIHODMHG74VDSOXAINANCNFSM4TNTYY3Q>.
>

2020-11-12 21:39 UTC, Dev1an commented
@duvrai Ik heb het aangepast. Moet jij die dan nog eens goedkeuren?

2020-11-12 22:16 UTC, d0rable approved these changes
ok! mooi zo

2020-11-12 22:20 UTC, merged